class Keys:
    """ ключи доступа к словарным значениям """

    DOCTORS = 'Doctors'
    DOCTOR = "Doctor"
    NURSES = "Nurses"
    NURSE = "Nurse"
    DEVICES = "Devices"
    DEVICE = "Device"
    ORGANS = "Organs"
    ORGAN = "Organ"
    ENDOS = "Endos"
    ENDO = "Endo"
    HOSPITAL = "Hospital"
    HOSPITALS = "Hospitals"
    PATHOLOGY = "Pathology"
    PATHOLOGYS = "Pathologys"
    COMPANY = "Insurance_company"
    COMPANYS = "Insurance_companys"
    MED_MANIPULATION = "Med_manipulation"
    MED_MANIPULATIONS = "Med_manipulations"
    BIOPSY = "Biopsy"
    BIOPSYS = "Biopsys"
    COMPLICATION = "Complication"
    COMPLICATIONS = "Complications"
    REASON = "Reason"
    REASONS = "Reasons"
    IENDO = "IEndo"
    IENDOS = "IEndos"
